# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
	:disks => {
			}

		
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            	  vb.customize ["modifyvm", :id, "--memory", "1024"]
                  needsController = false
		  boxconfig[:disks].each do |dname, dconf|
			  unless File.exist?(dconf[:dfile])
				vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                                needsController =  true
                          end

		  end
                  if needsController == true
                     vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
                     boxconfig[:disks].each do |dname, dconf|
                         vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                     end
                  end
          end
 	  box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
	  yum install -y java wget
	  echo export JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk>>/etc/profile
	  echo export JRE_HOME=/usr/lib/jvm/jre>>/etc/profile
	  source /etc/profile
	  cd ~
	  wget https://downloads.apache.org/kafka/2.4.0/kafka_2.11-2.4.0.tgz
	  tar -xvf kafka_2.11-2.4.0.tgz
	  mv kafka_2.11-2.4.0 /opt
	  cat>/etc/systemd/system/zookeeper.service<<'EOF'
[Unit]
Description=Zookeeper server
Requires=network.target
After=network.target

[Service]
Type=simple
ExecStart=/opt/kafka_2.11-2.4.0/bin/zookeeper-server-start.sh /opt/kafka_2.11-2.4.0/config/zookeeper.properties
ExecStop=/opt/kafka_2.11-2.4.0/bin/zookeeper-server-stop.sh

[Install]
WantedBy=multi-user.target
EOF

	  cat>/etc/systemd/system/kafka.service<<'EOF'
[Unit]
Description=Kafka server
Requires=zookeeper.service
After=zookeeper.service

[Service]
Type=simple
ExecStart=/opt/kafka_2.11-2.4.0/bin/kafka-server-start.sh /opt/kafka_2.11-2.4.0/config/server.properties
ExecStop=/opt/kafka_2.11-2.4.0/bin/kafka-server-stop.sh
Restart=on-failure
SuccessExitStatus=143
MemoryLimit=200M
LimitAS=3G
LimitCPU=50
LimitNOFILE=500
LimitNPROC=20

[Install]
WantedBy=multi-user.target
EOF
  	  SHELL
      end
  end
end
