# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
	:disks => {
			}

		
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            	  vb.customize ["modifyvm", :id, "--memory", "1024"]
                  needsController = false
		  boxconfig[:disks].each do |dname, dconf|
			  unless File.exist?(dconf[:dfile])
				vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                                needsController =  true
                          end

		  end
                  if needsController == true
                     vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
                     boxconfig[:disks].each do |dname, dconf|
                         vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                     end
                  end
          end
 	  box.vm.provision "shell", inline: <<-SHELL
          yum install -y httpd
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
          sed -i 's:/etc/sysconfig/httpd:/etc/sysconfig/httpd-%I:' /usr/lib/systemd/system/httpd.service
          mv /usr/lib/systemd/system/httpd.service /usr/lib/systemd/system/httpd@.service
          mv /etc/sysconfig/httpd /etc/sysconfig/httpd-first
          cp /etc/sysconfig/httpd-first /etc/sysconfig/httpd-second
          sed -i 's:#OPTIONS=:OPTIONS=-f conf/first.conf:' /etc/sysconfig/httpd-first
          sed -i 's:#OPTIONS=:OPTIONS=-f conf/second.conf:' /etc/sysconfig/httpd-second
          cp /etc/httpd/conf/httpd.conf /etc/httpd/conf/second.conf
          cp /etc/httpd/conf/httpd.conf /etc/httpd/conf/first.conf
          sed -i 's:Listen 80:listen 8080:' /etc/httpd/conf/second.conf
          echo PidFile /var/run/httpd-second.pid>>/etc/httpd/conf/second.conf
          systemctl start httpd@first
          systemctl start httpd@second
  	  SHELL
      end
  end
end
